name: "Terraform"

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Your name/initials to use as a prefix for your aws resources"
        required: true
      branch:
        description: "The branch to build"
        required: true
        default: "development"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.inputs.branch }}

      - name: Create test provider
        run: |
          branch=${{ github.event.inputs.branch }}
          echo ${branch//[\/]/\-}

      # - name: Create test provider
      #   run: |
      #     cp -r ./providers ./providers-test
      #     cd ./providers-test

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     terraform_version: 1.1.9 # TODO get this from somewhere?

      # - name: Terraform Init
      #   id: init
      #   working-directory: ./providers-test
      #   run: terraform init
      #
      # - name: Terraform Tfvars
      #   id: tfvars
      #   working-directory: ./providers-test
      #   run: |
      #     cat << EOF > terraform.tfvars
      #       prefix = "${{ github.event.inputs.prefix }}"
      #     EOF
      #
      # - name: Terraform Plan
      #   id: plan
      #   working-directory: ./providers-test
      #   run: terraform plan -no-color -input=false
        # continue-on-error: true

      # - name: Terraform Plan Status
      #   if: steps.plan.outcome == 'failure'
      #   run: exit 1

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false
